# Form implementation generated from reading ui file 'GUI/uis/HelpWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Help(object):
    def setupUi(self, Help):
        Help.setObjectName("Help")
        Help.resize(601, 429)
        self.closeButton = QtWidgets.QPushButton(parent=Help)
        self.closeButton.setGeometry(QtCore.QRect(240, 390, 100, 30))
        self.closeButton.setObjectName("closeButton")
        self.helpBrowser = QtWidgets.QTextBrowser(parent=Help)
        self.helpBrowser.setGeometry(QtCore.QRect(10, 10, 571, 371))
        self.helpBrowser.setObjectName("helpBrowser")

        self.retranslateUi(Help)
        QtCore.QMetaObject.connectSlotsByName(Help)

    def retranslateUi(self, Help):
        _translate = QtCore.QCoreApplication.translate
        Help.setWindowTitle(_translate("Help", "Form"))
        self.closeButton.setText(_translate("Help", "Закрыть"))
