# Form implementation generated from reading ui file 'GUI/uis/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.natButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.natButton.setGeometry(QtCore.QRect(690, 70, 100, 30))
        self.natButton.setObjectName("natButton")
        self.intButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.intButton.setGeometry(QtCore.QRect(690, 140, 100, 30))
        self.intButton.setObjectName("intButton")
        self.ratButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ratButton.setGeometry(QtCore.QRect(690, 210, 100, 30))
        self.ratButton.setObjectName("ratButton")
        self.polButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.polButton.setGeometry(QtCore.QRect(690, 280, 100, 30))
        self.polButton.setObjectName("polButton")
        self.helpButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.helpButton.setGeometry(QtCore.QRect(690, 340, 100, 30))
        self.helpButton.setObjectName("helpButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.natButton.setText(_translate("MainWindow", "Натуральные"))
        self.intButton.setText(_translate("MainWindow", "Целые"))
        self.ratButton.setText(_translate("MainWindow", "Рациональные"))
        self.polButton.setText(_translate("MainWindow", "Многочлены"))
        self.helpButton.setText(_translate("MainWindow", "Справка"))
